create table section and style it
GSG-G10/Trading-View---team-4 pull request #13
Opened 2021-07-27 16:15 UTC by ameera-abed

Related #3

2021-07-27 18:37 UTC, ahmadfarid-059 requested changes

2021-07-27 18:37 UTC, ahmadfarid-059 commented on index.html
> +            </table>
This table should be removed. We created data by DOM

2021-07-28 06:41 UTC, muhammadharoun approved these changes

2021-07-28 07:55 UTC, M7Mansour approved these changes

2021-07-28 11:24 UTC, closed without merging